### ISSUE TITLE
Verifying accounts and blank signatures

### ISSUE THREAD

**Issue by colbygk** [jacob-g/swiki-confirmaccount#16]
An issue reported by jacob-g related to the scratch wiki account confirmation process was failing because the host the wiki runs on had an entry in `/etc/hosts` for scratch.mit.edu that pointed directly to the edge server for the site, instead of leaving it open to the fastly CDN. That entry has been removed and now the confirmaccount module is once again able to access the site-api backend.

No errors were being written to the logs about this error. Had the response from the site-api being written to the logs this would have been easier to notice and fix.

I've created a pull request to add in logging to the LLK master branch copy of swiki. LLK/swiki-confirmaccount#8

**Comment by jacob-g** [comment]
This was fixed a while back, so I'm going to close it.
